name: Rendering Bug Report
description: File a rendering bug report.
title: "[Bug]: "
labels: ["rendering bug"]
assignees:
  - alexzhirkevich
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Please describe what happened, attach the bug screenshot and the screenshot of what you expect to see (from AE or other Lottie player). You can attach images by clicking this area to highlight it and then dragging files in.
      placeholder: Tell us what you see!
      value: "A rendering bug happened!"
    validations:
      required: true
  - type: checkboxes
    id: unsupported-features
    attributes:
      label: Unsupported features 
      description: Please check that your animation is not using [unsupported features](https://lottiefiles.com/supported-features) that are the same as for Lottie-Android. 
      options:
        - label: My animation doesn't use unsupported features
    validations:
      required: true
  - type: input
    id: compottie-version
    attributes:
      label: What Compottie version do you experience the bug on?
      description: "Note: only Compottie 2.0+ rendering bugs can be fixed because Compottie was using platform renderers before"
      placeholder: 2.x.x
    validations:
      required: true
  - type: dropdown
    id: platforms
    attributes:
      label: What platforms are you seeing the problem on?
      multiple: true
      options:
        - All
        - Android
        - iOS
        - Desktop
        - Web (JS)
        - Web (wasm)
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Does Compottie logs anythyng to the sdtout / your logger set with `Compottie.logger`?
      description: This can be warning or exception. Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
